# Site settings
title: Your awesome title
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
